namespace prontuario.Domain.Enums;

public enum PositionType
{
    RECEPCTION,
    MANAGEMENT,
    DOCTOR,
    NURSE,
    NURSING_TECHNICIAN,
    PHYSIOTHERAPIST,
    PSYCHOLOGIST,
    NUTRITIONIST,
    PHARMACEUTICAL,
    OCCUPATIONAL_THERAPIST,
    BIOCHEMICAL,
    X_RAY_TECHNICIAN,
    LABORATORY_TECHNICIAN,
}
