// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using prontuario.Infra.Database;

#nullable disable

namespace prontuario.Infra.Database.SqLite.EntityFramework.Migrations
{
    [DbContext(typeof(ProntuarioDbContext))]
    [Migration("20241215220701_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("prontuario.Infra.Database.SqLite.EntityFramework.Models.AccessCode.AccessCodeModel", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExperationDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsUserUpdatePassword")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("AccessCodes");
                });

            modelBuilder.Entity("prontuario.Infra.Database.SqLite.EntityFramework.Models.AddressModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<long>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PatientId")
                        .IsUnique();

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("prontuario.Infra.Database.SqLite.EntityFramework.Models.EmergencyContactDetailsModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<long>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PatientId")
                        .IsUnique();

                    b.ToTable("EmergencyContactDetails");
                });

            modelBuilder.Entity("prontuario.Infra.Database.SqLite.EntityFramework.Models.PatientModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("Date");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("Rg")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sus")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("prontuario.Infra.Database.SqLite.EntityFramework.Models.Permission.PermissionModel", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("prontuario.Infra.Database.SqLite.EntityFramework.Models.Profile.ProfileModel", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("prontuario.Infra.Database.SqLite.EntityFramework.Models.ProfileContainsPermission.ProfileContainsPermissionModel", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("PermissionId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("ProfileId");

                    b.ToTable("Profile_Contains_Permissions");
                });

            modelBuilder.Entity("prontuario.Infra.Database.SqLite.EntityFramework.Models.ServiceModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateService")
                        .HasColumnType("Date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<long>("PatientId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("prontuario.Infra.Database.SqLite.EntityFramework.Models.User.UserModel", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<long>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("prontuario.Infra.Database.SqLite.EntityFramework.Models.AccessCode.AccessCodeModel", b =>
                {
                    b.HasOne("prontuario.Infra.Database.SqLite.EntityFramework.Models.User.UserModel", "User")
                        .WithOne("AccessCode")
                        .HasForeignKey("prontuario.Infra.Database.SqLite.EntityFramework.Models.AccessCode.AccessCodeModel", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("prontuario.Infra.Database.SqLite.EntityFramework.Models.AddressModel", b =>
                {
                    b.HasOne("prontuario.Infra.Database.SqLite.EntityFramework.Models.PatientModel", "PatientModel")
                        .WithOne("AddressModel")
                        .HasForeignKey("prontuario.Infra.Database.SqLite.EntityFramework.Models.AddressModel", "PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PatientModel");
                });

            modelBuilder.Entity("prontuario.Infra.Database.SqLite.EntityFramework.Models.EmergencyContactDetailsModel", b =>
                {
                    b.HasOne("prontuario.Infra.Database.SqLite.EntityFramework.Models.PatientModel", "PatientModel")
                        .WithOne("EmergencyContactDetailsModel")
                        .HasForeignKey("prontuario.Infra.Database.SqLite.EntityFramework.Models.EmergencyContactDetailsModel", "PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PatientModel");
                });

            modelBuilder.Entity("prontuario.Infra.Database.SqLite.EntityFramework.Models.ProfileContainsPermission.ProfileContainsPermissionModel", b =>
                {
                    b.HasOne("prontuario.Infra.Database.SqLite.EntityFramework.Models.Permission.PermissionModel", "Permission")
                        .WithMany("ProfileContainsPermission")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("prontuario.Infra.Database.SqLite.EntityFramework.Models.Profile.ProfileModel", "Profile")
                        .WithMany("ProfileContainsPermission")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("prontuario.Infra.Database.SqLite.EntityFramework.Models.ServiceModel", b =>
                {
                    b.HasOne("prontuario.Infra.Database.SqLite.EntityFramework.Models.PatientModel", "PatientModel")
                        .WithMany("ServicesModel")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PatientModel");
                });

            modelBuilder.Entity("prontuario.Infra.Database.SqLite.EntityFramework.Models.User.UserModel", b =>
                {
                    b.HasOne("prontuario.Infra.Database.SqLite.EntityFramework.Models.Profile.ProfileModel", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("prontuario.Infra.Database.SqLite.EntityFramework.Models.PatientModel", b =>
                {
                    b.Navigation("AddressModel")
                        .IsRequired();

                    b.Navigation("EmergencyContactDetailsModel")
                        .IsRequired();

                    b.Navigation("ServicesModel");
                });

            modelBuilder.Entity("prontuario.Infra.Database.SqLite.EntityFramework.Models.Permission.PermissionModel", b =>
                {
                    b.Navigation("ProfileContainsPermission");
                });

            modelBuilder.Entity("prontuario.Infra.Database.SqLite.EntityFramework.Models.Profile.ProfileModel", b =>
                {
                    b.Navigation("ProfileContainsPermission");
                });

            modelBuilder.Entity("prontuario.Infra.Database.SqLite.EntityFramework.Models.User.UserModel", b =>
                {
                    b.Navigation("AccessCode")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
