// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using prontuario.Infra.Database;

#nullable disable

namespace prontuario.Infra.Database.SqLite.EntityFramework.Migrations
{
    [DbContext(typeof(ProntuarioDbContext))]
    [Migration("20250124003139_AddColunmSignsAndSymptomsToAnamneseTable")]
    partial class AddColunmSignsAndSymptomsToAnamneseTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("prontuario.Domain.Entities.AccessCode.AccessCodeEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExperationDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsUserUpdatePassword")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("AccessCodes");
                });

            modelBuilder.Entity("prontuario.Domain.Entities.Address.AddressEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("Neighborhood")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<long?>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Street")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.ComplexProperty<Dictionary<string, object>>("Cep", "prontuario.Domain.Entities.Address.AddressEntity.Cep#CEP", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .HasMaxLength(11)
                                .HasColumnType("TEXT");
                        });

                    b.HasKey("Id");

                    b.HasIndex("PatientId")
                        .IsUnique();

                    b.ToTable("Addresses", (string)null);
                });

            modelBuilder.Entity("prontuario.Domain.Entities.Anamnese.AnamneseEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Allergies")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AllergiesType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("AntecPathological")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AntecPathologicalType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("BloodPressure")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("BloodType")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Diabetes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Glucose")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("HeartRate")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("Height")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("MedicalHypothesis")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long>("MedicalRecordId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MedicationInUseType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("MedicationsInUse")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NecesPsicobio")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PreviousSurgeries")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("RespiratoryRate")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("Saturation")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("SignsAndSymptoms")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Temperature")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseOfProthesis")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Weight")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.ComplexProperty<Dictionary<string, object>>("ClassificationStatus", "prontuario.Domain.Entities.Anamnese.AnamneseEntity.ClassificationStatus#ClassificationStatus", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("TEXT");
                        });

                    b.HasKey("Id");

                    b.HasIndex("MedicalRecordId")
                        .IsUnique();

                    b.ToTable("Anamneses");
                });

            modelBuilder.Entity("prontuario.Domain.Entities.EmergencyContactDetails.EmergencyContactDetailsEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<long>("PatientId")
                        .HasColumnType("INTEGER");

                    b.ComplexProperty<Dictionary<string, object>>("Phone", "prontuario.Domain.Entities.EmergencyContactDetails.EmergencyContactDetailsEntity.Phone#Phone", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .HasMaxLength(15)
                                .HasColumnType("TEXT");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Relationship", "prontuario.Domain.Entities.EmergencyContactDetails.EmergencyContactDetailsEntity.Relationship#Relationship", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .HasMaxLength(30)
                                .HasColumnType("TEXT");
                        });

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("EmergencyContactDetails", (string)null);
                });

            modelBuilder.Entity("prontuario.Domain.Entities.MedicalRecord.MedicalRecordEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ServiceId")
                        .HasColumnType("INTEGER");

                    b.ComplexProperty<Dictionary<string, object>>("Status", "prontuario.Domain.Entities.MedicalRecord.MedicalRecordEntity.Status#MedicalRecordStatus", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("TEXT");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("StatusInCaseOfAdmission", "prontuario.Domain.Entities.MedicalRecord.MedicalRecordEntity.StatusInCaseOfAdmission#MedicalRecordStatus", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .HasMaxLength(20)
                                .HasColumnType("TEXT");
                        });

                    b.HasKey("Id");

                    b.HasIndex("ServiceId")
                        .IsUnique();

                    b.ToTable("MedicalRecords", (string)null);
                });

            modelBuilder.Entity("prontuario.Domain.Entities.Nursing.NursingEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NursingNote")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("PatientId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Nursing", (string)null);
                });

            modelBuilder.Entity("prontuario.Domain.Entities.Patient.PatientEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("MotherName")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("SocialName")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.ComplexProperty<Dictionary<string, object>>("Cpf", "prontuario.Domain.Entities.Patient.PatientEntity.Cpf#CPF", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(15)
                                .HasColumnType("TEXT");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Phone", "prontuario.Domain.Entities.Patient.PatientEntity.Phone#Phone", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .HasMaxLength(15)
                                .HasColumnType("TEXT");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Rg", "prontuario.Domain.Entities.Patient.PatientEntity.Rg#RG", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .HasMaxLength(15)
                                .HasColumnType("TEXT");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Status", "prontuario.Domain.Entities.Patient.PatientEntity.Status#PatientStatus", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .HasMaxLength(30)
                                .HasColumnType("TEXT");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Sus", "prontuario.Domain.Entities.Patient.PatientEntity.Sus#SUS", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .HasMaxLength(15)
                                .HasColumnType("TEXT");
                        });

                    b.HasKey("Id");

                    b.ToTable("Patients", (string)null);
                });

            modelBuilder.Entity("prontuario.Domain.Entities.Profile.ProfileEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.ComplexProperty<Dictionary<string, object>>("Role", "prontuario.Domain.Entities.Profile.ProfileEntity.Role#Role", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("TEXT");
                        });

                    b.HasKey("Id");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("prontuario.Domain.Entities.Service.ServiceEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ServiceDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceStatus")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("Services", (string)null);
                });

            modelBuilder.Entity("prontuario.Domain.Entities.User.UserEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FirstAccess")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<long>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.ComplexProperty<Dictionary<string, object>>("Cpf", "prontuario.Domain.Entities.User.UserEntity.Cpf#CPF", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(15)
                                .HasColumnType("TEXT");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Email", "prontuario.Domain.Entities.User.UserEntity.Email#Email", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");
                        });

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("prontuario.Domain.Entities.AccessCode.AccessCodeEntity", b =>
                {
                    b.HasOne("prontuario.Domain.Entities.User.UserEntity", "User")
                        .WithOne("AccessCode")
                        .HasForeignKey("prontuario.Domain.Entities.AccessCode.AccessCodeEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("prontuario.Domain.Entities.Address.AddressEntity", b =>
                {
                    b.HasOne("prontuario.Domain.Entities.Patient.PatientEntity", "Patient")
                        .WithOne("AddressEntity")
                        .HasForeignKey("prontuario.Domain.Entities.Address.AddressEntity", "PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("prontuario.Domain.Entities.Anamnese.AnamneseEntity", b =>
                {
                    b.HasOne("prontuario.Domain.Entities.MedicalRecord.MedicalRecordEntity", "MedicalRecord")
                        .WithOne("Anamnese")
                        .HasForeignKey("prontuario.Domain.Entities.Anamnese.AnamneseEntity", "MedicalRecordId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("MedicalRecord");
                });

            modelBuilder.Entity("prontuario.Domain.Entities.EmergencyContactDetails.EmergencyContactDetailsEntity", b =>
                {
                    b.HasOne("prontuario.Domain.Entities.Patient.PatientEntity", "Patient")
                        .WithMany("EmergencyContactDetailsEntity")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("prontuario.Domain.Entities.MedicalRecord.MedicalRecordEntity", b =>
                {
                    b.HasOne("prontuario.Domain.Entities.Service.ServiceEntity", "Service")
                        .WithOne("MedicalRecordEntity")
                        .HasForeignKey("prontuario.Domain.Entities.MedicalRecord.MedicalRecordEntity", "ServiceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Service");
                });

            modelBuilder.Entity("prontuario.Domain.Entities.Service.ServiceEntity", b =>
                {
                    b.HasOne("prontuario.Domain.Entities.Patient.PatientEntity", "PatientEntity")
                        .WithMany("ServicesEntity")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PatientEntity");
                });

            modelBuilder.Entity("prontuario.Domain.Entities.User.UserEntity", b =>
                {
                    b.HasOne("prontuario.Domain.Entities.Profile.ProfileEntity", "Profile")
                        .WithMany("Users")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("prontuario.Domain.Entities.MedicalRecord.MedicalRecordEntity", b =>
                {
                    b.Navigation("Anamnese");
                });

            modelBuilder.Entity("prontuario.Domain.Entities.Patient.PatientEntity", b =>
                {
                    b.Navigation("AddressEntity")
                        .IsRequired();

                    b.Navigation("EmergencyContactDetailsEntity");

                    b.Navigation("ServicesEntity");
                });

            modelBuilder.Entity("prontuario.Domain.Entities.Profile.ProfileEntity", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("prontuario.Domain.Entities.Service.ServiceEntity", b =>
                {
                    b.Navigation("MedicalRecordEntity");
                });

            modelBuilder.Entity("prontuario.Domain.Entities.User.UserEntity", b =>
                {
                    b.Navigation("AccessCode")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
